services:
  - type: web
    name: smart-hiring-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: REDIS_ENABLED
        value: true
      - key: MONGOOSE_CONNECTION
        value: mongodb+srv://your-mongodb-connection-string
      - key: HUGGING_FACE_TOKEN
        value: your-hugging-face-token-here
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password

  - type: redis
    name: smart-hiring-redis
    plan: free
    ipAllowList: []