services:
  - type: web
    name: smart-hiring-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: REDIS_ENABLED
        value: true
      - key: REDIS_HOST
        fromService:
          type: redis
          name: smart-hiring-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: smart-hiring-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: smart-hiring-redis
          property: password
      - key: MONGOOSE_CONNECTION
        value: mongodb+srv://your-mongodb-connection-string
      - key: accessKeyId
        value: your-aws-access-key
      - key: secretAccessKey
        value: your-aws-secret-key
      - key: region
        value: your-aws-region

  - type: redis
    name: smart-hiring-redis
    ipAllowList: []
    plan: free 